// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxehmuxxymtxcwayhbcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4ZWhtdXh4eW10eGN3YXloYmNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDg3NjQsImV4cCI6MjA2NTQ4NDc2NH0.kPTt1hr4eMAFp86kDvrA18cL9bzxEFHrngreOxkj-co";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);